### ISSUE TITLE
Prepare release 1.0.0

### ISSUE THREAD

**Issue by davidorme** [ImperialCollegeLondon/pyrealm#206]
This is to provide a meta issue as a checklist of things to do for a release 1.0.0:

- [x] Drop Python 3.9 #196 
- [x] Testing milestone:
    - [x] Adopt new unit tests, closing #23
- [x] SPLASH milestone:
   - [x] Close #165,
   - [x] Close #192
- [x] Subdaily milestone:
    - [x] Close #72 
    - [x] ~Maybe close~ #82 ~but this could hang on for a next release.~ (Finicky - going to wait for next release).
    - [x] Check if #70 now covered and close.
    - [x] Remove the previous subdaily version and move over to new implementation, closing #197
    - [x] Rename `FastSlowScaler` (closed by #197)
- [x] Profiling milestone - refactor of profile.py (closed by #188)
- [x] Horner polyval (closed by #187)
- [x] Adopt trusted publishing (#198)
- [x] Run a dummy release to test publishing
- [x] Fix up the issues with the profiling system (closing #207)
- [x] Fix up the issues with the profiling system _again_ (closing #224 )
- [x] Update CONTRIBUTING to remove duplication and order the material better (closing #209)
- [x] Update CHANGES and README
- [x] Update package metadata to add new authors etc.

The issue also has an associated `release/1.0.0` branch which should be used for checking release candidates before merging into `main` and `develop`.

**Comment by MarionBWeinzierl** [comment]
Done
