### ISSUE TITLE
[Meta] Seasonal dynamics in leaf area

### ISSUE THREAD

**Issue by davidorme** [ImperialCollegeLondon/pyrealm#347]
This is a meta issue to coordinate tasks needed to implement a new model of the seasonal dynamics in leaf area.

### Theoretical background

The theoretical background of this issue builds on two recent papers from Lemontree:

1. Cai et al. (2023) "A unifying principle for global greenness patterns and trends" [bioRxiv](https://doi.org/10.1101/2023.02.25.529932). This paper establishes a simple model for global greenness as the minimum of water and energy limitations to productivity. It generates a prediction of annual maximum fraction of absorbed photosynthetically active radiation (fAPAR, $f_{APAR}$)  from the predictions of the P Model for a year, plus some additional data on precipitation and aridity.
2. Zhou et al (2024) "A general model for the seasonal to decadal dynamics of leaf area" [bioRkiv](https://doi.org/10.1101/2024.10.23.619947). This paper takes the predicted annual maximum $f_{APAR}$ from above, along with the resulting predicted leaf area index LAI, and then uses this information to calculate daily time series within modelled years of the steady state and realised LAI to give seasonal patterns.

### Implementation

These issues follow the suggested steps in the attached word document describing the calculations.

- [ ] Calculation of annual fAPAR and LAI values from a fitted PModel and precipitation data
- [ ] Calculate tunable parameter $m$ defined as the ratio of steady state annual LAI to GPP.
- [ ] Calculate the steady state LAI.
- [ ] Calculate the realised LAI given a lagged process.

TODO - needs more work to unpack this

**Comment by davidorme** [comment]
This new approach can be used to calculate a daily LAI prediction for a site, so provides an alternative route to generating LAI for use in e.g. the two leaf model.

**Comment by j-emberton** [comment]
> This new approach can be used to calculate a daily LAI prediction for a site, so provides an alternative route to generating LAI for use in e.g. the two leaf model.

ah ok, I get it now

**Comment by j-emberton** [comment]
Hi @MarionBWeinzierl , would you like to pick up this work stream?
