### ISSUE TITLE
Restructure shared functions into a common core

### ISSUE THREAD

**Issue by davidorme** [ImperialCollegeLondon/pyrealm#75]
**Is your feature request related to a problem? Please describe.**

The draft `splash` module (#69) has a bunch of functions that overlap substantially with existing functions in the `pmodel` module. The two sets of functions need to be reconciled but also relocated - they are general utility functions that are shared across modules, so logically are better placed outside those specific science modules. As a precursor to the integration of `splash` it makes sense to have a more logical home for that common code.

**Describe the solution you'd like**

Create a `pyrealm.core` module that incorporates these functions in sensible groupings. That probably also brings in the `hygro` and `utilities` modules, to give `pyrealm.core`, `pyrealm.const` and then particular science/model based modules like the `pmodel`, `tmodel`, `splash` etc.

**Describe alternatives you've considered**

There are enough of these functions that just having small modules for each one would make a more cluttered namespace. Gathering them as submodules under a single module seems cleaner.

Edited to add subtasks (still in progress):

- [x] Create `core` module.
- [x] Move `utilities` into `core` and fix references and documentation.
- [x] Create a new `core` documentation section to describe the functionality in the `core` module
- [x] Move `hygro` module into `core` and fix references and documentation.
- [x] Constants restructure - base constants class definition should be `core` and `hygroConsts` should move with `hygro` module (maybe move _into_ `hygro`), but then other classes move into the appropriate science modules? We then need to unpack `PModelConsts`. Not sure about this one yet! (This is #76 .)
- [x] Inspect `pmodel.functions` to separate out `core` from `pmodel` functions.
- [ ]

**Comment by davidorme** [comment]
Possibly separate the different constants classes out so that there are core constants for the core utilities and then specific constants classes for different science submodules.

**Comment by MarionBWeinzierl** [comment]
@MarionBWeinzierl to create core module, add const and hygro and utilities.
@davidorme to look at tmodel, pmodel, splash etc

**Comment by MarionBWeinzierl** [comment]
@davidorme is going to break this up into a checklist or sub issues

**Comment by MarionBWeinzierl** [comment]
I am wondering whether it would make sense to have two separate core modules for physics-specifics calculations such as in hygro, and general utilities. Maybe a tree-like module structure with core as root, then physics and utilities, and then whatever fits under those two subheadings? Can the constants be divided into those two groups, too, or are they all physics (I just find physics constants, looking briefly through it)?

**Comment by davidorme** [comment]
I don't think we need to make it tree-like. That does make import names a bit longer and I'm not sure we need to differentiate beyond `core` and science modules. I think we make it flat for now, but maybe we end up grouping them if the core grows.

**Comment by davidorme** [comment]
Yes, it is.
